package com.project.MilitaryManagement.payload.response;

import lombok.With;

import java.util.Date;

@With
public record QuanNhanResponse (
    Long id,
    String hoTenKhaiSinh,
    String hoTenThuongDung,
    String ngayThangNamSinh,
    String soHieuQuanNhan,
    String canCuocCongDan,
    String danToc,
    String capBac,
    String chucVu,
    String tonGiao,
    String thanhPhanGd,
    String thanhPhanBanThan,
    String nguyenQuan,
    String hoKhau,
    String nhapNgu,
    String donViCSM,
    String ngayVaoDoan,
    String ngayVaoDang,
    String ngayChinhThuc,
    String trinhDoHocVan,
    String ngoaiNgu,
    String tiengDanToc,
    String chuyenMonDaoTao,
    String chuyenMonTuHoc,
    Integer sucKhoe,
    String benhLy,
    Double chieuCao,
    Double canNang,
    String khiChat,
    String soThichCaNhan,
    String truocNhapNgu,
    String lyDoNhapNgu,
    String suyNghiMoiTruong,
    String nguyenVongBanThan,
    String chiTietCMKT,
    String diaChiDiPhep,
    String nguoiBaoTin,
    String diaChiNguoiBaoTin,
    String soDienThoaiBaoTin,
    String hoTenCha,
    String ngaySinhCha,
    String sdtCha,
    String tinhTrangCha,
    String ngayTuTranCha,
    String ngheNghiepCha,
    String chucVuCha,
    String coQuanCha,
    Boolean laDangVienCha,
    String sucKhoeCha,
    String benhLyCha,
    String noiOHienNayCha,
    String hoTenMe,
    String ngaySinhMe, String sdtMe,
    String tinhTrangMe,
    String ngayTuTranMe,
    String ngheNghiepMe,
    String chucVuMe,
    String coQuanMe,
    Boolean laDangVienMe,
    String sucKhoeMe,
    String benhLyMe,
    String noiOHienNayMe,
    String honNhanChaMe,
    String kinhTeGiaDinh,
    Integer soAnhEm,
    Integer soAnhEmTrai,
    Integer soAnhEmGai,
    Integer conThuMay,
    Integer soAnhEmLaCanBo,
    String sdtLienLacGiaDinh,
    String thongTinOngBaNoi,
    String thongTinOngBaNgoai,
    String hoTenBanGai,
    String ngaySinhBanGai,
    String diaChiBanGai,
    String sdtBanGai,
    String hoTenBanTrai,
    String ngaySinhBanTrai,
    String diaChiBanTrai,
    String sdtBanTrai,
    String nguoiAnhHuongTichCuc,


    String statusOngNoi,
    Date ngayMatOngNoi,
    String statusBaNoi,
    Date ngayMatBaNoi,
    String ghiChuNoi,

    String statusOngNgoai,
    Date ngayMatOngNgoai,
    String statusBaNgoai,
    Date ngayMatBaNgoai,
    String ghiChuNgoai,

    String dienBienNgayThang,
    String dienBienCanBo,
    String dienBienNoiDung,
    String dienBienCuThe,
    String hoTenCBDP1,
    String chucVuCBDP1,
    String sdtCBDP1,
    String hoTenCBDP2,
    String chucVuCBDP2,
    String sdtCBDP2
){
}
