package com.project.MilitaryManagement.payload.request;

import lombok.With;

import java.util.Date;

@With
public record QuanNhanRequest<ngaySinhCha, sdtCha, ngayMatOngNoi, statusBaNoi, ngayMatBaNoi, statusOngNgoai, ngayMatOngNgoai, statusBaNgoai, ngayMatBaNgoai, nguoiBaoTin>(
        Long id,
        long [] ids,
        String hoTenKhaiSinh,
        String hoTenThuongDung,
        String ngayThangNamSinh,
        String danToc,
        String tonGiao,
        String thanhPhanGd,
        String thanhPhanBanThan,
        String nguyenQuan,
        String hoKhau,
        String nhapNgu,
        String donViCSM,
        String ngayVaoDoan,
        String ngayVaoDang,
        String ngayChinhThuc,
        String trinhDoHocVan,
        String ngoaiNgu,
        String tiengDanToc,
        String chuyenMonDaoTao,
        String chuyenMonTuHoc,
        Integer sucKhoe,
        String benhLy,
        Double chieuCao,
        Double canNang,
        String khiChat,
        String soThichCaNhan,
        String truocNhapNgu,
        String lyDoNhapNgu,
        String suyNghiMoiTruong,
        String nguyenVongBanThan,
        String chiTietCMKT,
        String diaChiDiPhep,
        String hoTenVo,
        String ngaySinhVo,
        String diaChiVo,
        String sdtVo,
        Integer soConTrai,
        Integer soConGai,
        String thongTinChiTietCon,
        String nguoiBaoTin,
        String diaChiNguoiBaoTin,
        String soDienThoaiBaoTin,
        String hoTenCha,
        String ngaySinhCha,
        String sdtCha,
        String tinhTrangCha,
        String ngayTuTranCha,
        String ngheNghiepCha,
        String chucVuCha,
        String coQuanCha,
        Boolean laDangVienCha,
        String sucKhoeCha,
        String noiOHienNayCha,
        String hoTenMe,
        String ngaySinhMe, String sdtMe,
        String tinhTrangMe,
        String ngayTuTranMe,
        String ngheNghiepMe,
        String chucVuMe,
        String coQuanMe,
        Boolean laDangVienMe,
        String sucKhoeMe,
        String noiOHienNayMe,
        String honNhanChaMe,
        String kinhTeGiaDinh,
        Integer soAnhEm,
        Integer soAnhEmTrai,
        Integer soAnhEmGai,
        Integer conThuMay,
        Integer soAnhEmLaCanBo,
        String sdtLienLacGiaDinh,
        String thongTinOngBaNoi,
        String thongTinOngBaNgoai,
        String hoTenBanGai,
        String ngaySinhBanGai,
        String diaChiBanGai,
        String sdtBanGai,
        String hoTenBanTrai,
        String ngaySinhBanTrai,
        String diaChiBanTrai,
        String sdtBanTrai,
        String nguoiAnhHuongTichCuc,
        String canBoDiaPhuongTinNhiem,

        String statusOngNoi,
        Date ngayMatOngNoi,
        String statusBaNoi,
        Date ngayMatBaNoi,
        String ghiChuNoi,

        String statusOngNgoai,
        Date ngayMatOngNgoai,
        String statusBaNgoai,
        Date ngayMatBaNgoai,
        String ghiChuNgoai
) {
}

